from tracker.charts import (
    btc_historical_returns,
    btc_terminal_price,
    btc_cycles_roi,
    btc_cycles_roi_peak,
    btc_qt_bear_markets,
    btc_ytd_roi,
    treasury_yield_curve,
    treasury_yield_spreads,
)


CHARTS = [
    {
        "name": "Treasury Yield Spreads",
        "slug": "treasury_yield_spreads",
        "category": "Macro",
        "quick": ["Rates"],
        "assets": [],
        "summary": "Slope between two Treasury maturities with optional S&P 500 overlay.",
        "preview": "background: linear-gradient(140deg, rgba(248,113,113,0.35), rgba(96,165,250,0.15));",
        "renderer": treasury_yield_spreads.render,
    },
    {
        "name": "Treasury Yield Curve",
        "slug": "treasury_yield_curve",
        "category": "Macro",
        "quick": ["Rates"],
        "assets": [],
        "summary": "Term structure across maturities with smoothing and log scaling.",
        "preview": "background: linear-gradient(140deg, rgba(56,189,248,0.35), rgba(20,184,166,0.2));",
        "renderer": treasury_yield_curve.render,
    },
    {
        "name": "Treasury Deposits With Federal Reserve Banks",
        "slug": "treasury_deposits",
        "category": "Macro",
        "quick": ["Rates"],
        "assets": [],
        "summary": "Treasury cash balance held at the Fed (FRED series).",
        "preview": "background: linear-gradient(140deg, rgba(148,163,184,0.35), rgba(59,130,246,0.15));",
        "renderer": None,
    },
    {
        "name": "Bitcoin ROI After Cycle Bottom",
        "slug": "bitcoin_cycles_roi",
        "category": "Crypto",
        "quick": ["Growth"],
        "assets": ["BTC"],
        "summary": "ROI from each cycle bottom across Bitcoin market cycles.",
        "preview": "background: linear-gradient(140deg, rgba(168,85,247,0.3), rgba(34,197,94,0.2));",
        "renderer": btc_cycles_roi.render,
    },
    {
        "name": "Bitcoin ROI After Cycle Peak",
        "slug": "bitcoin_cycles_roi_peak",
        "category": "Crypto",
        "quick": ["Growth"],
        "assets": ["BTC"],
        "summary": "ROI from each market cycle peak to the next bottom.",
        "preview": "background: linear-gradient(140deg, rgba(251,191,36,0.3), rgba(94,234,212,0.2));",
        "renderer": btc_cycles_roi_peak.render,
    },
    {
        "name": "QT Ending Bear Markets",
        "slug": "qt_ending_bear_markets",
        "category": "Crypto",
        "quick": ["Growth"],
        "assets": ["BTC"],
        "summary": "BTC ROI from QT bear-market peaks into their subsequent bottoms.",
        "preview": "background: linear-gradient(140deg, rgba(96,165,250,0.35), rgba(244,114,182,0.2));",
        "renderer": btc_qt_bear_markets.render,
    },
    {
        "name": "Year-To-Date ROI",
        "slug": "year_to_date_roi",
        "category": "Crypto",
        "quick": ["Growth"],
        "assets": ["BTC"],
        "summary": "BTC annual ROI from Jan 1 through each calendar year.",
        "preview": "background: linear-gradient(140deg, rgba(56,189,248,0.28), rgba(251,191,36,0.18));",
        "renderer": btc_ytd_roi.render,
    },
    {
        "name": "Bitcoin Historical Returns",
        "slug": "bitcoin_historical_returns",
        "category": "Crypto",
        "quick": ["Growth"],
        "assets": ["BTC"],
        "summary": "BTC monthly, quarterly, and yearly returns with halving-cycle filters.",
        "preview": "background: linear-gradient(140deg, rgba(16,185,129,0.28), rgba(96,165,250,0.22));",
        "renderer": btc_historical_returns.render,
    },
    {
        "name": "Bitcoin Terminal, Realized & Balanced Price",
        "slug": "bitcoin_terminal_realized_balanced_price",
        "category": "Crypto",
        "quick": ["Growth"],
        "assets": ["BTC"],
        "summary": "BTC price with terminal, realized, and balanced valuation bands.",
        "preview": "background: linear-gradient(140deg, rgba(248,113,113,0.30), rgba(34,197,94,0.18));",
        "renderer": btc_terminal_price.render,
    },
]


def get_chart_map():
    return {chart["name"]: chart for chart in CHARTS}
